### PR TITLE
Fick BOS. Alle mein kerle hasse BOS.

### PR DESCRIPTION
**Pull request by ProfessorPopoff**
Fuck em. I hate em. You hate em. Everyone hates them. Soyboys cry about Brotherhood and there they are. This took me all of five minutes. Merge it or don't, for all I care you can not merge it specifically to laugh at all the salt lords. You do you, champ! 

image
(The current state of the BOS pictured above)

### CODE REVIEW

**Comment by Zach720** [comment]
cum

**Comment by ProbablyCarl** [comment]
Removal in such a fashion isn't proper. I'll likely go through and disable them myself, but this seems like a saltPR with no effort behind it.

**Comment by Mannybrado** [comment]
> Removal in such a fashion isn't proper. I'll likely go through and disable them myself, but this seems like a saltPR with no effort behind it.

shut up. duhhhhhhhhhh "salt pr" shut up. BoS have been broken since BD and always will be. Everyone wants this.

**Comment by Mannybrado** [comment]
Having a quarter of the people on the map be locked away in their own little retard bunker, never interacting with anyone but themselves, is dogshit. Nothing will fix this, I absolutely guarantee it.

**Pull request closed without merging**
