### PR TITLE
Removes a Matrix from Sunnydale

### PR DESCRIPTION
**Pull request by ProfessorPopoff**
##Description
Yeah... Cyber merged my PR right before I could go ahead and commit this in. Speedmerge time. Read no further.

turns this 
image

into this 
image

and nothing more...

### CODE REVIEW

**Review by ProfessorPopoff — COMMENTED** [review]
looks good here....

**Comment by scarwolff** [comment]
As maintainer I APPROVE this PR

**Review by scarwolff — APPROVED** [review]
make sure scarwolff = Elder too

**Review by scarwolff — APPROVED** [review]
awesome changes, BOS cant powergame despawn no more 👍

**Review by scarwolff — APPROVED** [review]
ummmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm yeh 👍

**Comment by scarwolff** [comment]
ready to launch 👍

**Pull request closed without merging**
