### PR TITLE
Peenmaster's Sprites

### PR DESCRIPTION
**Pull request by SquishyOranges**
## Description
On behalf of the homosexual Peenmaster, I am making a pull request of his sprites because he is too retarded to make one sadly.

## Motivation and Context
New Sprites = Good

## How Has This Been Tested?
Local machine 
## Screenshots (if appropriate):
image
image

## Changelog (necessary)
:cl:
add: Wall Sprite
add: Door Sprites
/:cl:

### CODE REVIEW

**Comment by RemBestWaifu** [comment]
I have prepared every walwl combination possiblee yes i am retarded and do not kno how o use github, i make sprites with ms paint yes. I'll ifnissh the other alls if this one epasses. ❤️

**Comment by FulminatingGold** [comment]
Yes yes,,,,,,,, I am CUMING at the though,,....

**Comment by ProbablyCarl** [comment]
The 'vertical' doors function as an icon? Because as is, it doesn't look like it'll work without additional changes.
Especially so given that two other files have been deleted, despite possibly being a dependency.

**Comment by RemBestWaifu** [comment]
vertical doors are supposed to work the same as horizontal doors, just that they're vertical whenever they're on the left or right side of a building, not upper part or bottom part.

**Comment by SquishyOranges** [comment]
I'ma close this gay ass PR.

**Pull request closed without merging**
