### PR TITLE
Comments Gender Reassignment Surgery out of The Code

### PR DESCRIPTION
**Pull request by waterwater1212**
really have no idea how they're doing gender reassignment surgery in the wastes anyways

## Description

You can't do gender reassignment surgery, top or bottom, anymore. You can still castrate people though. It's still in the code in case anyone wanted it back for some reason...
## Motivation and Context

This removes the ability for meta-ERP-cliques from turning their friends into big mommy dom futa for the 52nd round in a row. Also, I don't see how filthy wasteland doctors would be performing gender reassignment surgery.
## How Has This Been Tested?

Tested on local server, works like a charm.
## Changelog (necessary)
:cl:
del: Removes Gender Reassignment Surgery
/:cl:

### CODE REVIEW

**Comment by Mannybrado** [comment]
😳

**Comment by Zebraman** [comment]
Frick you kidnaping and sex changing Legion is tradition

**Comment by imw-Oculus** [comment]
Removing features for one's personal ethical/political reasons doesn't sit particularly well with me.

**Comment by waterwater1212** [comment]
Here's what doesn't sit right with me: Neon haired ERP fiends who are meta-friends giving each other dicks so they can enhance their purple text and play with one hand harder. Sure, maybe it's funny or immersive or whatever to change someone's gender, but you have to realise how it's actually being used. ERP fiends getting off to shemales. Just saying, bro.

**Comment by imw-Oculus** [comment]
If someone is breaking a rule, they're breaking a rule. Otherwise, I understand your frustration, but there's nothing that should be done.

**Comment by CaptainSlumbo** [comment]
this is good, I like this very much

**Comment by FantasticFwoosh** [comment]
Based.

**Comment by ErwinSnowden** [comment]
based and redpilled.

**Comment by waterwater1212** [comment]
merge this

**Comment by Zebraman** [comment]
Rad storm, fev, radiation in general and DNA scanner can sexchange you and the only way to threat that is surgery. If you plan to remove everything I mentioned because you are afraid that some neon hair erper would abuse it to do their lrp bullshit then you have the tism.

**Comment by ProbablyCarl** [comment]
This is unironically required to fix a few things. As mentioned above. Removal for the sake of removal is icky.

**Pull request closed without merging**
