### PR TITLE
Hopeful AMR Rebalance

### PR DESCRIPTION
**Pull request by ProbablyCarl**
Causes the AMR to knock you on your ass all but 5% when firing from the hip.

### CODE REVIEW

**Comment by Nigkgro99** [comment]
So you mean that it'll knock you back and stun you?

**Comment by ProbablyCarl** [comment]
No. It'll stun you temporarily, causing you to drop it and any other handheld item, alongside making you prone for a second or so.

**Comment by githubuser4141** [comment]
I think it sounds funny, but maybe it should only trigger if you fire it while on the move? It'd be strange for a veteran ranger to fire their rifle when 'unprepared'.

**Comment by ProbablyCarl** [comment]
It's a bit odd, yes. We're going to give this a go for the upcoming round, but depending on how it works out I'll edit it as required. Likely going to do as you suggested, @githubuser4141.

**Comment by Nigkgro99** [comment]
Yeah, I think it should just be knocked out of your hands and stun you if you fire it while moving. iirc the vet rangers in fnv had AI that told them to stop and look down the scope when they fired instead of running and gunning with it, so it'd be accurate. Sort of

**Pull request merged**
