### PR TITLE
NCR base and Legion update ( super high quality )

### PR DESCRIPTION
**Pull request by Hyperstellarwithguns**
## Description
I replaced the old NCR base with a new one and edited the legion field to have the animals in a separate pen. I have changed the "Random gun" in the bunker north of legion to a tier 4 spawner

## Motivation and Context
Most of the NCR base was not used and I believe this would improve gameplay in removing unused parts and resizing the entire base to something more appropriate. The loot spawners are still the same in the armory. As for the Legion, I wanted to separate the animals from the field to make making poultice for the legion easier and less of a hassle.  I also wanted the bunker north of legion to be worthwhile. 

## How Has This Been Tested?
No. :flushed: ( but I swear no space turf ) 

## Screenshots (if appropriate): 
legionpen
NCRbase

## Changelog (necessary)

add: New NCR base
add: New Legion animal pen
balance: Replaced one random gun spawn with (1) singular (one) T4 weapon spawn 
del: Old NCR base.
del: Old Legion animal pen

### CODE REVIEW

**Comment by Mannybrado** [comment]
Looks good. Main issues I see the gate, dirt overlays on the sidewalk/road, THE FUCKING CHEM DISPENSERS, and they don't have their water barrels(the "three" barrel that has a shitload of water in it). There's also a lot of free shit that they previously would have had to go out to get(sandbags/wood), but whatever. I would add a hair razor to the captain's room, maybe also a photocopier in the office in the same building. Yessir.

**Comment by Mannybrado** [comment]
image
these wont be powered because they aren't in the NCR area. you'll have to extend it out for any lights that are outside, which will also create retarded holes in the weather, but there's no other way to have outside lights work.

**Comment by Mannybrado** [comment]
the extra stimpaks are kind of shitty, but whatever.

**Comment by Mannybrado** [comment]
image

**Comment by Hyperstellarwithguns** [comment]
> 
> 
> image
>feature
I fixed that and the areas.
Added the photocopier and razor to the captain's room and the three barrels of water.

**Comment by Mannybrado** [comment]
epic

**Comment by ProbablyCarl** [comment]
No chemistry setup, please. They can obtain it elsewhere.

**Comment by ProbablyCarl** [comment]
I'm assuming this is dead. I'll be closing it due to lack of replies. If this changes, feel free to DM me on Discord.

**Pull request closed without merging**
