### PR TITLE
General dungeon balance changes

### PR DESCRIPTION
**Pull request by Mannybrado**
## Description

Changes a lot. Various locations that had nothing now actually have at least a dogshit item spawn, various buffs and nerfs to locations mostly on Pahrump. This doesn't necessarily mean its on par with Sunnydale.
RadX is slightly rarer in general, Sunnydale now has radsuits in it.
The biggest changes are behind the commie vault. The changes listed are relevant for both maps.

- The previous dorm lockdown shutters are now extended to every place in the vault except the generators(power is needed to open the shutter) and security.
- Pahrump's version now has an APC and SMES units, as well as general changes to make it into a place people can actually clean up and live in.
- Old Glory has been removed and replaced. The Centaur that was there isn't anymore, it is now Jeff.
- There is now only one NVG in engineering. Also, it is protected by a robobrain.
- There is now very good things in the cave, as well as a lot more radiation. You can no longer mine into it from the back, not like anyone does this anyways. This is hopefully going to be coupled with the glowing one rad burst, which will make the cave an incredibly difficult place to clear. We'll see.
- Turrets have been added to the main crossroads and outside the overseer's office.
- All of the ghouls in the main halls have been replaced with robots.
- The overseer's chinese pistol has been replaced. The chinese pistol has replaced the mosins in the armory.
## Motivation and Context

cuz lol
## How Has This Been Tested?

locally
## Screenshots (if appropriate):
find out in game metarusher
## Changelog (necessary)
:cl:
i gotta feeling woohoo that tonights gonna be a good night that tonights gonna be a good night that tonights gonna be a good  good night, i feel it woohoo that tonights gonna be a good night that tonights gonna be a good night that tonights gonna be a good good night
/:cl:

### CODE REVIEW

**Comment by SquishyOranges** [comment]
Why have you done this?... Do you just want to hear the cry of metarushers?

**Comment by Nigkgro99** [comment]
as long as the loot at the end is actually as advertised??????????????

**Comment by ProbablyCarl** [comment]
Good shit.
Ready to merge?

**Comment by Mannybrado** [comment]
yes

**Pull request merged**
