### PR TITLE
Uncucks xenobio

### PR DESCRIPTION
**Pull request by ErwinSnowden**
this is needed for more /vault-gimmickry/

## Description
Undid a bunch of stupid moves by adam el-tablaway to make xenobio unfun when it should be the go to gimmick creator for the vault.

## Motivation and Context
xenobio is one of the only things to do as vault beyond botany, which is already overpowered as fuck and can be used to say, obtain the mutation toxins via strange seeds/mutagen doses anyway? also you can make super kudzu that eats the entire map if you have the knowhow, I might do it sometime. Xenobio is already super difficult since slimes are always hostile to humans and how we lack slime processors, this makes it more tolerable.

## How Has This Been Tested?
all of this has existed in the past, it didn't cause problems then. the friendly mobs spawn friendly mobs like cows and can be used for agriculture, the other extracts can be used as they always have.

## Changelog (necessary)
:cl:
balance: Added back a heap of reactions to xenobio, making more slimes useful without jeopardizing balance.
/:cl:

### CODE REVIEW

**Comment by Mannybrado** [comment]
Strange Reagent was removed by BD because it was OP, but carl added it back in because................
I dunno. Adding in more ways to powergame isn't, uhhhhhhhhhhhhhhhhhhhhhh. Good. At all. Human mutation toxin shouldn't even exist anyways.

**Comment by ErwinSnowden** [comment]
> Strange Reagent was removed by BD because it was OP, but carl added it back in because................
> I dunno. Adding in more ways to powergame isn't, uhhhhhhhhhhhhhhhhhhhhhh. Good. At all. Human mutation toxin shouldn't even exist anyways.
> Kinda cringe!

vault is the only faction with xenobio, furthermore, converting subhuman mutants into pure Aryan humans is something that could be fun. also how is this even powergame? all i did were add back some features that were removed, i do not see how friendly mobs from gold cores could be a dis-benefit nor do i see how they could be powergamed.

in short, use an actual argument next time.

**Comment by FantasticFwoosh** [comment]
It'd be nice honestly though if we could pinch some aspects of contempoary vatgrowing FEV xenobiology alongside this.

**Comment by Zebraman** [comment]
We don't need vaulter spawning sentient deathclaw or sentry bot, which they'll be able to do with gold and light pink.

**Comment by ProbablyCarl** [comment]
Vault disabled. If there's a reason we re-enable it, and don't do this in a rework, this may be reopened.

**Pull request closed without merging**
