### PR TITLE
General Fixes and Reverts

### PR DESCRIPTION
**Pull request by cyberth0t**
Re-added the stun mechanic from throwing bodies at other players because it never should have gotten removed. Opens up new avenues of gameplay.

Most, if not all, mobs will continue to attack you whether you are (un)conscious

replaced the powerfist sprite with the old one because the dr sprite is ugly

also re-added the cross-beam explosion

### CODE REVIEW

**Comment by Tennessee116** [comment]
Will knockdown still force people to drop items? I remember in other places that being an issue.

**Comment by ProbablyCarl** [comment]
oh god oh fuck they found us

**Comment by cyberth0t** [comment]
You're getting knocked over, so of course you're going to drop any items in your hands. It's only an issue if you suck

**Comment by Tennessee116** [comment]
> oh god oh fuck they found us

Always checked around in hope it'd return.

**Comment by ProbablyCarl** [comment]
> > oh god oh fuck they found us
> 
> Always checked around in hope it'd return.

Soon:tm:

**Pull request merged**
