### PR TITLE
More hotkeys

### PR DESCRIPTION
**Pull request by Sneakyrat6**
## Description
Adds 3 hotkeys:
U-Rest
Y-Whisper
L-LOOC

Tweaks to shift+E and shift+B

- Fixed the inhand not updating when storing an item with these hotkeys
- Allows the hotkeys to draw from the equipment slot instead of just a storage item that would be equipped(ie if you have a stunbaton on your belt slot you can draw it with shift+e now even if you dont have a sec belt)

## Motivation and Context
more hotkeys make game better, also other servers already have these

## How Has This Been Tested?
Yes, I ran it on local and tested each keybinding, including in the other hotkey mode that you get when you hit tab(the one where you need to hold ctrl while playing, I also updated the hotkeys help info so just read that if you dont get what I mean)

## Changelog
:cl: Sneakyrat
add: Added 3 hotkeys: V for Rest, Y for Whisper, and L for LOOC
tweak: Shift+E and shift+B allows the hotkeys to draw from the equipment slot instead of just a storage item that would be equipped
fix: Fixed the held item sprite not updating when storing an item with shift+E and shift+B
/:cl:

### CODE REVIEW

**Comment by Zach720** [comment]
[ Squeaking ] Well, well. Look at the city slicker pulling up in his fancy German car. This car was made in Guatemala. Well, pardon us, Mr. Gucci Loafers. I bought these shoes from a hobo. Well, la-dee-da, Mr. Park Avenue Manicure. I'm sorry. I believe in good grooming. You're not gonna grow nothin' on the old Simpson place. That's why your daddy abandoned it. Oh, what do you know? Well, I know your soil p.H. is up around 9.6, and you need it seven to eight max. Oh, that's just superstition! You watch me. I'll grow something out there. Not if you're plantin' gummy bears. D'oh!

**Comment by Sneakyrat6** [comment]
[ Squeaking ] Weww, weww. Wook at the city swickew puwwing up in his fancy Gewman caw. This caw was made in Guatemawa. Weww, pawdon us, Mw. Gucci Woafews. I bought these shoes fwom a hobo. Weww, wa-dee-da, Mw. Pawk Avenue Manicuwe. I'm sowwy. I bewieve in good gwooming. You'we not gonna gwow nothin' on the owd Simpson pwace. That's why youw daddy abandoned it. Oh, what do you know? Weww, I know youw soiw p.H. is up awound 9.6, and you need it seven to eight max. Oh, that's just supewstition! You watch me. I'ww gwow something out thewe. Not if you'we pwantin' gummy beaws. D'oh!

**Comment by Mannybrado** [comment]
you should port alt-arrowkey too
ok

**Comment by Sneakyrat6** [comment]
> you should port alt-arrowkey or emmmmmmm vision locking or whatever too

code for that doesn't exist already afaik so it seems out of scope for something small like this, plus alt is already used to toggle walk @Mannybrado

**Comment by Sneakyrat6** [comment]
but anything thats a verb takes like 5 seconds to add as a keybinding so lmk if theres any requests for verb hotkeys

**Comment by ProbablyCarl** [comment]
Looks good, man. Let me know when you're ready to have this merged, and I'll go ahead and do such.

**Comment by Sneakyrat6** [comment]
I moved the rest hotkey from v to u since thats tg and a few other server's default and that seems to be a more common standard. But yeah looks ready to merge @ProbablyCarl

**Comment by ProbablyCarl** [comment]
Test merging for a few rounds and then we'll merge it fully.

**Pull request merged**
