### PR TITLE
MP + Prod Hotfix

### PR DESCRIPTION
**Pull request by Tennessee116**
## Description
NCR Military Police have had their shotgun and beanbag ammo removed, and have been given a riot shield along with a facewrap.

The prod, which MPs use, has been debuffed to use more charge and have less stunforce.

MPs are also clearly told in their job descriptions they are not frontline soldiers.

## Motivation and Context

This slightly fixes how unbalanced stun combat is, and allows MPs to be reintroduced, a relatively important part in keeping everyone in the NCR in check.

Also I miss MPs, but that's personal.

## How Has This Been Tested?

- I can't test how people react to descriptions of jobs, nor can I test any loopholes people can use with a riot shield, so that goes in untested.

- The changes to the stun prod were tested on a slightly older /tg/-based server, right now the only local fork I have on my PC, I put the values in and tested it out against a regular human. Some humans took two stuns to go down, and others took one stun but got up quicker than usual. This is a variable I cannot explain.

- This code is relatively independent of other areas, and should not affect anything directly outside of its intention.

## Changelog (necessary)
:cl:
tweak: Tweaked the loadout of the NCR MP to have a riot shield instead of a riot shotgun, and added a desert facewrap for them.
balance: Rebalanced the stun prod to take more charge each hit, and stun less each hit.
/:cl:

## Author's Note

This was made in thirty minutes by a man who plays MP. There is bound to be _some_ issues, I just can't find them.

### CODE REVIEW

**Comment by CaptainSlumbo** [comment]
I think the stun prod is fine where it is, what's the point in nerfing the stun prod if they aren't going to ever use them on anyone but disobedient troopers. MP's help keep troopers in check which is good for everyone all around.

**Comment by Sparrowbird611** [comment]
Alright, feel free to correct me if I'm wrong on this, but as I recall on current tg code, stun force ignores armor. I'd personally set said weapon to around 35-40 stun force, depending on whether or not you want slowdown on the first hit. This makes it better than the bo staff still, (It was about 20 if I'm remembering correctly) but also means you can still potentially out DPS him in melee if you bring better gear and out skill him.

**Comment by Tennessee116** [comment]
> I think the stun prod is fine where it is, what's the point in nerfing the stun prod if they aren't going to ever use them on anyone but disobedient troopers. MP's help keep troopers in check which is good for everyone all around.

The problem with what you said is that is _optimal_. The stun prod and MP role needs to be balanced to make it less appealing to rush into the frontlines against the Centurion.




> Alright, feel free to correct me if I'm wrong on this, but as I recall on current tg code, stun force ignores armor. I'd personally set said weapon to around 35-40 stun force, depending on whether or not you want slowdown on the first hit (Working on slightly old knowledge, as I believe you acquire damage slowdown at 40 dmg). This makes it better than the bo staff still, (It deals 19 stam per hit) but also means you can still potentially out DPS him in melee if you bring better gear and out skill him.

I think, for now, it should stay at 75, and if it needs further nerfing, it can go lower.

**Comment by Sparrowbird611** [comment]
Understandable.

**Comment by ProbablyCarl** [comment]
Removed the stun baton altogether for all in map jobs. Took the rest of the PR and cut and paste it.
Will be closing this.

**Pull request closed without merging**
