### PR TITLE
Xander tweak.

### PR DESCRIPTION
**Pull request by Schwaglord**
## Description

Modifies the age and maturation related variables to regulate their growth pattern.

## Motivation and Context

Makes it so that the plant shows their sprites fully, and doesnt look stupid by having maturated at 1 age. (see their counterpart broc)

## How Has This Been Tested?
This has been tested on a local machine and is working properly.

## Changelog (necessary)
:cl:
tweak: Xander has been updated with a new growth pattern.
/:cl:

### CODE REVIEW

**Comment by imw-Oculus** [comment]
IMO, Xander and Broc both need a reagent revert to what they were in mid-era BD/DMG. Could fold that into this PR.

**Comment by ProbablyCarl** [comment]
Adjust the crafting recipe to be one-one again, too, if you'd be so kind.

**Comment by Schwaglord** [comment]
I see, i will investigate both situations and try finding a solution.

**Comment by imw-Oculus** [comment]
> Adjust the crafting recipe to be one-one again, too, if you'd be so kind.

Eh. Healing Powder is pretty robust. I think it's fine with 2-2.

**Comment by FantasticFwoosh** [comment]
Its wrong because you use wild xander which only has two states.

**Pull request merged**
